version: '3.1'

services:

    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
        depends_on:
            - db

    migrations:
        image: boxfuse/flyway
        command: -url=jdbc:mysql://db -schemas=checklists -user=root -password=root -connectRetries=60 migrate
        volumes:
            - ./db-scripts:/flyway/sql
        depends_on:
            - db